namespace: freshrss

resources:
  - namespace.yml
  - secret.yml
  - pvc.yml
  - replicaset.yml
  - service.yml
  - ingress.yml

configMapGenerator:
  - name: freshrss
    envs:
      - config/freshrss.env
