kind: ReplicaSet
apiVersion: apps/v1
metadata:
  name: freshrss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: freshrss
  template:
    metadata:
      labels:
        app: freshrss
    spec:
      containers:
      - name: freshrss
        image: freshrss/freshrss:1.19.2
        envFrom:
        - configMapRef:
            name: freshrss
        - secretRef:
            name: freshrss
        env:
        - name: TZ
          value: "Europe/Berlin"
        - name: CRON_MIN
          value: '2,32'
        - name: FRESHRSS_USER
          value: |-
            --api_password ${FRESHRSS_ADMIN_API_PASSWORD}
            --email ${FRESHRSS_ADMIN_EMAIL}
            --language en
            --password ${FRESHRSS_ADMIN_PASSWORD}
            --user admin
        ports:
        - name: http
          containerPort: 80
        resources:
          requests:
            memory: 50Mi
            cpu: 50m
          limits:
            memory: 100Mi
            cpu: 100m
        volumeMounts:
          - mountPath: /var/www/FreshRSS/data
            name: freshrss-pv
            subPath: data
          - mountPath: /var/www/FreshRSS/extensions
            name: freshrss-pv
            subPath: extensions
      volumes:
        - name: freshrss-pv
          persistentVolumeClaim:
            claimName: freshrss-pvc