apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: miniflux
  namespace: miniflux
spec:
  encryptedData:
    MINIFLUX_ADMIN_PASSWORD: AgCRSxIqI6MO2Op97Ga+p0i6rsPEcvUos6LeUlEyrQwr+etUKtANkv2d0XpC583MQGNRjIjOHh3Z3CJ5McCTuV3+NBwIPBzVgpAaQVr1yokQtsLOD3ZHgzh/8u5/MEdPvqYge60OrsixsOiZdx7HUmxb8/obeWwT2W+OpNlJ72id3QqNqyIX2e49OU8dey9/2C7JtsdGB4n0EvigsHPaTYFRnbzy51B3yFYFT9t/Me+SrtEotYHKpXOPctw0u6s36zPPQrSJNsMc4xH7ujfOZcRnY3B0gGd879Wl7d93cnpcQOi5dUIvVmwF2XAdmXcTDFQULNS5Tb7urChnpYhFLNeJOqKtaAzb6tk357/sIDA1J9BVYg5ahv1w8o1y9ed38qqaPPz7cUYMvgIxfyjgurSx9D8mi6kOeNV3/8/wiUb+L/b668DuUKnTopdo6Ac3v4x3kniTYPEE8n/D3FC2ePymUrBILhjSIuW/R5uzDIORaInv8DSgCJcph0wE+o8GmlYIG8IfG70dBduENxqEYE3eQqEOZ4G+GxuhCPCmIA/sq7/bX2M3UEC2Ohc3eVCB5XwRD25xSSzpPoMThZMm9XFHpVbJOlG+0WfLkn4uS3k1jbZeYvnSxTI7rX24br3dMXBQNG10MzzIcy4ijgrkffXsfz05JMu0AnF5b9dpCNzgLSfNn5ULDTWgqQrm/DgM5HWtfynKcIV2Fbc0m2GjTkGO
    MINIFLUX_POSTGRES_PASSWORD: AgAp7FzqzDUYw+4+bZ+htDkas8BDd8vY8WlJiOtrJvDn7IwOaGDsEDeM5xYUlzB4mUzG7BD7mrlImnO9gG28htiCyxgUZdHmmTJY/rVT9SMnArFJJJ0kg7sdZKvaE6+fsl96HQJoDcQ7g61SBM7uiJcQ0TZ1Uzcnue5tJdEtNFF3/3S2T4q7yHeOtIo/NnrW8aQLHLEzdHd2Y8g2Yi6hSaQbpm2R5dnWK2H7k6SPoOfjpZx91rIGY43O4A5+/1BkB2WMgYFYUXfvSpt6CEVcIn7gf5D8QWhmIiFkkyvgkxPREoBZzLZBhpKdZAPZHqmt50dXpI2R+5ty1oAJDWBDRYT17AehIW1ai1BNuJy4lXSq6yEMXBhaBjr4Ffparg6gMzHMQXTlHlfoz2QZAHRJEAeBbNOhH4k0EQJArzayXSKT7lSVMJyDujcF5VklQb7ycwcRbTNnYR2z+hIX/xaODAtGhmZ32B1gxrtut1g++REf2B6J4Qpc7p3LccH4SoUKZxe+9Z5RkwfWbrXfH6ordi/6zec7ArkkvQX2SsdhqRx25AJpA2CsY3ugdY67llFVoCFEAzim524IP2UAdZ874Ph98DwQ79NtCsm+WM8S86z9BorDvASePPHoRuvO356IyUKVttCVpeKnlFozZpDmVjcyVsY9WGhHVHtPfBwjN4uSBVwtQWuELx7MwR9a0FhZxgZ7H2LQGhNdKk3U5PqBgI5w
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: miniflux
      namespace: miniflux

