apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: miniflux
  namespace: miniflux
spec:
  encryptedData:
    MINIFLUX_ADMIN_PASSWORD: AgA5B6XEn55x4exgehTLu8Lsak9/WHF4fADMchOnHECtrF1FyEq6K5kjukd5CUA8paEQtivHmtO1dGbxlr89Q0uldpjL1pBrJkMyGEdvRHaI1W1FYcsVGjmssobaC/BseL40wseEwAQd0Hip1CmEgtB9ZkmZhQt+Y/Exuc3/HQovL1DFO2oGE+J3WaxmeklqOQxsdlGw01Vl/qI9o36YxePjdFngxBMFMD9uPtlc3PZj370e7BoNkTw5d2RW4W05qq/qutSNEz1cp5t8nm2PKllsPIod7AxKHmEQeVM0aOSM/KadESrVJ++bmgQw2ZAsbUCNve0e8TDZoR2qBp2y/FPDk/cRnsvPTG4tl2/gm2eEMJ+GhogHMvS4FaLF1mP/2JD00noWMATTZJhvgkAXYhEhLrpA/JMSMF1iqefsVITqi8LEbvgW0IE4BI+lyWwmZTyLwYz4ekmZi+XVX1ugd2MFEbJgdawDcUjuDG1GpBrlMb9ogDee82CHPE1HHtrGtfPW13r+Jc3MsRqanviVb78xqZcMi0xHnkwjVeiPzQRXWjNmrtNYAgf7fTwwNMPT7u0GEKyNfGjM/icNZTJJuGsvhFbDPUb7+iPjHP0XnJYaR3wDPYjKTUIgYEL67K7OwfABpiD4PzZOfwXYbDUtxpHLikSRH5uvhhFqvpbTTQoflEmWrlF7M4v/q8ts+0NdBnDVbb248RvOtDfSMbvLmjgD
    MINIFLUX_POSTGRES_PASSWORD: AgCk906eaPlv6/g93gMXEFzDI9d997ZqX8Yxqo2r8DlIL3nmX/7tJk+1fKLs6JFCJlRz/9/ARHapqyGNRgqV8nq+5qKprBcRHK7onTlbpFJ0g4hOJGHzDrd1PUS3IJMAAETvNmk9uFFlIJMd/OPxa2pi7/MSzzqZ4s1769jkcSH+BJnMQsabAG9jq2dwHZC1bSGT/aAUst3cC7evh3fWsUCWOJ2mYznoCK+6Ta+yLkCwmcpwFr0UFNKYhwfOS5/eixI9dJJt8sNxBSxAEQqq1/sPnaI2NRly+pCklRFYxE5vVMlntZEkCH9hYmjS2WfPzmGDy2CuVaBOiTf1ML+vfAlMXIp66wCsHSLkzdLwiwzM7jFzrL7RWtrL9qwojbrJuNvbwae49X2LMrGNrKke3bui4x7qD/M7Q7eYsI7osheOMoFxVZApmidXwOeCEIFzPL2fs0lkD7o3PEvvnAfazhxycbnnkRhdy8QR7jYHqtROqnjYi6l4LZvdnemiXDyzJ4Lfdg3ILaBoL3u89D8GtCxOdyjCevrIS3YdXKoyCJN90+D9NNocFIxNh+uLnGFvUNWx/nJ46ULxw5KUMJTXPXNG8mpUPn8zj2xSBxQ2e5klUNQPz+Cd+UOwnPPmQZcTQRtQ+wFTp9CTQMKGSkDrHVHTnMDsc6fBeZrmXnnvATf2seSf55FjTQQVrum6BHfEhCI52J62NmaXse51pufsAgP4
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: miniflux
      namespace: miniflux

