apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: miniflux
  namespace: miniflux
spec:
  encryptedData:
    MINIFLUX_ADMIN_PASSWORD: AgCBM5Gyi7hxTHqdorZfb4ll3zH6ELC53DCghxGgctjVwdtxYS0BoKDmwIet/k1K6jhAtJZg+QN79SFWqxem+t1+jD1YPl5Rp2Vvp2K6WW9Vz7Tg509Triozh9UM/MS88WLJI4oTHtBSOmHixm0OPlGRrPynq1FkvtqMwmWS1jeSdf7SA5nXI2gftnHvi+DLnPHACubhTGB47r/Jc7KygugN/z/XoD04XaEBn3Rv7UfMFwa4E9ExCl5jmqL6iIw7FEs3q2uUtX6SHRsuU4Pg8H/8tQEQBGJTVVaTDO3bDUaAeyrcETT4f/SSh7lpNApC0Qi941kn5trQNVvrLAeBCR6ImGE/3dEJmukLlybrOK0zyzQ2TtEq7maNN/UNT7j2rENBwh933MyjZeP/kzFOU3892R5hKvq5/NQevUuYHzU0fXoxLWXtt+LT45jIwCn73Q0sneJpwrrZGq6J8YL2ENE6zYufMEP4jP81HFspKDqxPEKscc3gQJ6uvdISlWU6Gx7U2rDE3RNGXB8BMIfwkbei2aK0MSy+8cJMRMxvsofGPVTzgutezQjAt5FBf7m3WCetbuDajmYpLQOI8NLdzphQMcQ5DAhhEyGNsthPri4JXSdS7pT9sto57ONye2URiWwgeOFzvuT1DRmotrgD4IsnFEKma2zOPVbd3Y9EUsqHmxGxhOeeomojoxFrI2DZ/Zsqy85bMm8PC+I3VJMEM/24
    MINIFLUX_POSTGRES_PASSWORD: AgC4ywYV+ZcLHx6OdQK3gosB02/GFX5IG1Or7gG/vm4KyRCF7GVOkWeueploBBYWHcmfqaQ3zB+64/pd09TA+StniW+o+SEa91u1AYso8uuoUm9kmZq6YCYQS52jx//eZwDVXUDOU6yQG/51vrvec4zsoRNVd6Fs+wKMMl0Kl1R+Y2YqOZtgxy2GcnfuAY7Zc8IWI+ZzBHo4QoA/b9wVIa2ay5rsiXLlE9NuXVSYrDyMCaDjymTIxQ4u6JXOkTWaKF7nkwoXQ9tBU1/ks2drkFUZVa353mOYD89br70YxNdVeYDxUPPuoXMeboegpLwFIl1Rk8dBqgqNCq/Icovf1eXckzLnLJ27T9Dys1xIoJXG5n4BqhQZXRppGTsb1Be9ahAkEnC1iO/sncDTTqTqMIOqQGCfBSqbj429DufzcMxyzGTuyfJHJg+SEJscPdXZXoMdgV3vaHr1XhzPtd6SmyVLelK0tnb35Pc2gq/oy6xx9R2pj+eDH2bUeM9DUh88abGTFW5y9qUcOXwRdhs8sSUPdeL07VMjRIdvMAWNbcfgqA9f2oHZm3M6V+jVLC0zE+Dt+u2FBQPJ2KqySfkNfKf3Nb0jeQi+MxPTIWjvib74xnR7V/jT9N+QfTzNQG6nN275hWyP/ziVdLFLzdwIMrTZHe+bWteLcGr7cFEOkpbh1cHHhAt64ntoZued7z29xmu9GitXbk1Qv/bcQJ0uGuYN
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: miniflux
      namespace: miniflux

