apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: miniflux
  namespace: miniflux
spec:
  encryptedData:
    MINIFLUX_ADMIN_PASSWORD: AgChzn1KSyll2pesL5SOO7wDlRzV3UKKA6pKM/UvrCAht8TEIMn5VhCaFk/bhUmP3lXy4mt+BAnvj8obfjY15JKVrZwM7QZX2Bz72JQvwb42esW6HTxGJPmAsSCc94ABGLqnHUfIh42DdwmAfsXryhaSGeEQKJ4OoMXntqCieBby3CAi/n0VRsS0JOX5/nwo2h2MgH4bX526GtPOfH+SzAvcildWjSoj8SnLvM2l1f8xzAyvQyNU6qMED9L9CMCVUyKu0I2hyDgF0wFGcNK7AGwIn74xO+IbIXaT1A7PFwy/l7//YYx/TP5q5X6+ulll04uvkw8TpDZD0BhMxEgsbuke9UfFeqOkA4T7DBccu+y063FNzsgakzb2Kpdn6Q971un/se5OMeFPFP2A0OSKI0DwB0e1IAQJcVv3eBVN+nnuJiAaHdki72c3W3FaPBVzWp+r182otSc4DuqSe3HgsRr1bKUMMxxzf++szj43MdH+rtlmFf3vB21MHooUilFnWBzDsDQU6A8RWpEu4jDbP/dKt2euBqlo/zMyA8rsC4Mf6jOf7mHks70mEAsu6VO7W8GAt4Mg/VDfrFxXmmcojOizPfRbcOE0fj13/Ow8aS91fVLpFUJ4ebA4eDS+xSOgXJqlJTvM0aa++kfqh3g4kGp51DQDipzPaDfTXC6ZMnRYowxPYiPiXE1AT5LEg2tzTZajHI4Xt7H+VvQgOjxzU96G
    MINIFLUX_POSTGRES_PASSWORD: AgAFx3+mEJBjC7vYmVxuZS0cZr1HrykL5AtmQV/xUn1LdB6B/kyUfiCPo7cMAWLZ3Oyk4ZiC5wEJ5HqpR/aHBp4qJXotuUBPHY6PNfRgkOjJ4zHfE3IkO3FtQWB98+useC+2N2YkuL4/bO3nXVKki3GdjMmDu9aC0+ozygIUP7RzrZTyOuzJYaUgzUWwj1P55xa9LI8KsKNcQ8FUnipkjxewqSAlIAbRp+/bokIfWu1r7zf0n72F6RDtJ4rIsXTF6X66FPWMvlOuzL2r9CmgES7zmr83q44ulhj3dL/dvfsB2E+yOCN7/ZDRWIippe6sEay4/INuWPlOWLfdKAjtr54aDlbvU9ePKuBjhLbP14w6OGDxPVsX+oXgkKbxOhrBPLNkKAgNZLoqavO3NO2NavPs96WICELC4KOh2Uv6CY9cHaAjiXlI8/m3mylajZJJEHZ4h6BlBPdRWU2HbN7p9cAFG/cohl6YUsCyIQzomziRG4gh+t7n19JzD6uiy6y1q4JmIABO4AVf3QgLS3wB6gD0oNShFHEJN9bk+9rD0N9ES0gt4sdS86RH6HCFJvKxOwd/hTgpTMaITevXoGgF9/MAhi9HeY9rV9S9yY62RohzcnjZzPTsPIJHDIE1C4EKG1QOhwDdSZ9VIPXJ/U6v8RJBx95+gvrMDaPzLMDz4ZWp+YZzOGX+Jynlez3BPAgM/G/uREB1xIFHe2/OBCGlAmSb
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: miniflux
      namespace: miniflux

