---
k3s_cluster:
  hosts:
    htz-nbg1-0:
      ansible_host: 78.46.201.114
      ip: 10.0.1.1
      k3s_control_node: true
    htz-fsn1-0:
      ansible_host: 49.12.219.73
      ip: 10.0.1.2
      k3s_control_node: true
    htz-nbg1-1:
      ansible_host: 168.119.170.212
      ip: 10.0.1.3
      k3s_control_node: true