---

# We're adding k3s_control_node to each host, this can be done in host_vars/
# or group_vars/ as well - but for simplicity we are setting it here.
k3s_cluster:
  hosts:
    k8s-0:
      ansible_user: root
      ansible_host: 116.203.215.169
      ansible_python_interpreter: /usr/bin/python3
      k3s_control_node: true
    k8s-1:
      ansible_user: root
      ansible_host: 94.130.186.142
      ansible_python_interpreter: /usr/bin/python3
      k3s_control_node: true
    k8s-2:
      ansible_user: root
      ansible_host: 188.34.195.78
      ansible_python_interpreter: /usr/bin/python3
      k3s_control_node: true