kind: Deployment
apiVersion: apps/v1
metadata:
  name: miniflux
spec:
  replicas: 2
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: miniflux
  template:
    metadata:
      labels:
        app: miniflux
    spec:
      containers:
      - name: miniflux
        image: miniflux/miniflux:2.0.37
        envFrom:
        - configMapRef:
            name: miniflux
        - secretRef:
            name: miniflux
        env:
        - name: RUN_MIGRATIONS
          value: "1"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: miniflux.miniflux-db.credentials.postgresql.acid.zalan.do
              key: password
        - name: DATABASE_URL
          value: "postgres://miniflux:$(POSTGRES_PASSWORD)@miniflux-db.miniflux.svc.cluster.local/miniflux"
        ports:
        - name: http
          containerPort: 8080
        resources:
          requests:
            memory: 20Mi
            cpu: 50m
          limits:
            memory: 50Mi
            cpu: 100m