apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: miniflux
  namespace: miniflux
spec:
  encryptedData:
    MINIFLUX_ADMIN_PASSWORD: AgDOjXh4E6jNTLOWoyEryXC+nfNCAGLY2ge6rUPF28JC86pqUxV9yWgzyG5qDmv/gxTGH5KHeGzfjlbt03Dg/33ngDog5FKLbNwQXw2VpNjmod/aebuqwxJm3JfLLYrRsgKBdPoq5rBnY7k0U0RdGTqouq2AeE63ucLOlK9OypfY9Y8tH/1I/AyXiRPh+mlhCbTErUync9QEpVl2i5SYfLaBftf36w1Du57Mgwx+hyfp0r+DAL/1cBdz0vRSw5anksnlUEmKiIOPjAUGIBzWt74/k4IqGxvGy9bGDKFnFxWtC5cEx4QgZ1E6nNkfsyOXxDHUY/IclMIuWhCRjlkdnEabJgs69rFKQtFRxD072PaY63EZqPkq5OLZogdHCkis0LcBSn62YhBmhpeb7wp1yod6o68Ma6GhlKUT/UVk15QYmjqOucDoPe0+JylcUyYbk8rzQGxynSVbcV/YDxYpuGg11MMphiTp/hXs1WFIIi5C9GJSnc2T4Xw1Cj5uezHbDsjWVX0VRURdvUDZy3GBh/Lxnsz2Oi0TS2xz9uvlBZuoBSNId/TR7I44ovojjy2ZPrqA7y0jOVEFVnBwrbuNkeHFUFPGRXVeGheh9f4yxCpK+7bKdEBnqJjfL6YFsIgXXeJ/jrOrYm7gNEBCthEmBwqRqICexclBKWHiqcTXrSP3YG/1efr3W2cRkvEO2QHm0TpcSrZ6IBTxLMSgNO8UPqOL
    MINIFLUX_POSTGRES_PASSWORD: AgAKWkqoZr0bjihAuJje0kOJCqSvbp6exHCMY4OaSVCLxLCL1bwdPyMcynvmV8qdUCKUWNF8dfXnQoE75t6IwlxdXMn7KSloGJ/N5gLo6tq1wnXlW2H0pGv+qnDB8gihfMFSKyEsoWPess47GtTNFpXPnFx9gxQhZfLKVObGxp8vlg/juQGg3sLhCVHe4gkGuWAo4BxLI0xfSIz7STrJERXvnhrr+X7BJAsR1vMjq05GNY2C4ENHy1f9+9vabtMekMG5Md/DLYqIf/wGQN2EFibS/DvWPxD8eEJea2U6qOGt/UdzbyM4pq0DCo5aaktKWBfdL1zPUatDxrzkrIM1G5nQIrsC54uWTCAXNgdBPk58Q6OQ+EyJUm8dGCUzfyGaE1Cn+iHt1Cd0VzI6lmAn7x/tzJ1js5qQpT4B3RuCBD6pReiEGtxbsaUItcB30pI7e3tf6hjE1UYXrkLgv2T9bQREtkKu+QJy5mU0W6veA2x6g9OnNBbeZDT2duoVPrkUDbkfAYRzMdT3aMzdE/GTiuYMLPw/wfTc2u+7cc0EbP+5LG03YVVEjcTnvaKEkqHSqH3JL8GMpzggHBlQyyzFo+VUpkRfHgXjM3h2VdyBWwNtED6nTJjKsTUG9H64elEkJcjBUbdC6MY7ZjPittTul65E4LtN/pIhZBuBm8DmVy4OmorkzahxHpthl6iOTpZUQrTU71N/IiGlQHAxOZec9Ce9
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: miniflux
      namespace: miniflux

