apiVersion: notification.toolkit.fluxcd.io/v1
kind: Receiver
metadata:
  name: webhook-receiver
spec:
  type: github
  events:
    - "ping"
    - "push"
  secretRef:
    name: webhook-token
  resources:
    - kind: GitRepository
      name: flux-system