MINIFLUX_POSTGRES_USER: miniflux
MINIFLUX_POSTGRES_PASSWORD: postgres
MINIFLUX_POSTGRES_DB: miniflux

MINIFLUX_ADMIN_USERNAME: admin
MINIFLUX_ADMIN_PASSWORD: admin
MINIFLUX_HOSTNAME: miniflux.slashdev.space

