apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hello-world
  namespace: default
spec:
  encryptedData:
    EXAMPLE_PASSWORD: AgBNC9qN3eruCXC/o3cwLg9J/P0QBtEaGyR/Z/d3czYvO6UTmtBLKW2BJ19ZQSHaC3qOCNRaTl9H3F8ztVK1LzU4tvllzeqNqFFQ3+PIZTmdgpsg/8ngYUUZH7ewUoUMoNQPDPepFNmxP/xnDKMeX7z45ZkPF99k78Cdwemp4RrooESRSzwhOmFtnPvjAQE2r/3k+ouYHqu1vlTp3d+Cene8e6lYMP/khyjqzMtf/k9dFQBAVK6Cyd9xDW+XU8cIW8R7n4TfZmcMTCos6nKa3g0xeluvoHc4Rc1Tim3IuOfIxXHYHkmOIWOaBF1aVbeH9N+i2h5ckESvkaEeYQFMLTk1zYzDljHdkEB0yaUs/mVEyEcdwQpR5N3+mAuCoTsr8KTDIOt3ZGF/WixILHOXhn/J1lFy3hVAE8EUs69UqCfTq0s9bxNHKH9qc9ML68JLHGXl3h42fEEVtDIshCU7IbfXITrmlKMS9W8ELW6WXP9ijuk6ytCRDffPnlPE1PftAENhs3PUTPZ7n6iL7JAvOX8ZXn1ew9b3mzSeQjnUUmv3WYtinE0fNFYd8GJs/78EhMKa8OBgxHUwllYjc2pOd5EhBtN/hej0p83MvPRVb8Tpok14QjweWjS8BU/Rb9r7AE6UmpS/QIsQTYXCQNF/lIrEPW6SOCdd/T/bwBfJRfTtcCGO8O+KbXuUBV1GTCYiNMhacjI=
    EXAMPLE_USER: AgBNLMKLQVaOAFu9XPTpq1KX0pkNhfxJSHVlLb2SB1asxkWE2RXT4fN3YNmm5pJV+vu/XAPwxnns4mQ0thxu7z4KlTuqZiXffVAw+oNIYHtEVynv9Hd4o+dWe/nXPAN3ta7IgmweZ7x7dtGQzkLuuQglD9/MIki5XxsguwCmpzrN86vppjRQ4ac6O867fIilOG+eocS33p3skHFRxKR/uVTtycR7J9uaQd5u3qYdcVP1iOVyTsHgXsyRcnkqxgqRXwIFVZPng9YmAdh/ZPZuljMCxgElgZvmbIfWXxpxxt2JtYolP26JRe3OWtJagwyf8D8bWsCY5IlI0j6iul9/P5tsXI83rWTw7pjDY81A36/dqeue4VUGthCC4fFf7J6yuh9UJKb4wabjOhlgI0n8rmB5jm60Ezo58XaoiKq263W7TJfISUtzyht8UDLOdnSxjxIHbodNa4UGPxi7gua0T3S2FCt14lkyGTmvp8tnfN+Nqa5Y2PhpSMydZr4FdRyRpD+UvalxzXXfIf130PNP4yPZrr+CMYZndqZysLu77gq7dIZ5WysNWAGqmIH1q8A0zv6ft+JNWUZ9iMnI/tNLltqXT8xLdbhgbYtwDky85o5yJKcLc2FXPx0pS7yFlyXQDXoP96+/GCqs9AgndcVwVbYk97Dse/tbz3cNWIztod3PIMKtq10TJlR5jFLYvjaIKW8F+ws=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: hello-world
      namespace: default

