apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hello-world
  namespace: default
spec:
  encryptedData:
    EXAMPLE_PASSWORD: AgCHWJ6IHdIIBF5Q0I3ZTlKyf0aS4QyxKT6H6iB9aq39M4MhE2VtYZMlOrAyZmYRkF+UiOHc08I/lSXvHhPvBlaZ6sYF4T52oK6IddjukAbCtbIfXH3x2xycjHNY2jFnFizSFov8emoL+FpqFlrDJR4Rxq3ysDghqoNAXrAQRt7Y6A6LSx0r/oHT6HICAcegIwA/5HNKI8uVnr/Rb85QqeGgbywYqHRugwpldlKLXkrnh2oPP0fa0pCHdXK0UXv1i1aDCU1/nitqHL2r4GV2ZTLTCgNFlFWOB2nDyE9SFWkqxhmaT/I2X1BSmygQ42dQbrtLirdse/+dtMzRiXzAauwzqIbDsizZPNkLyeINRmiF0H/zQ2U6RbSDFlgIVxSu3h06jw7WkiErW3bsTsdisW9njYYFrJCiWy95VvsflIT90rUsKcmoLneJU7FxK7tAU0Btr++S/F4qbzPAI30FbJebrn16PSAWQz8D7rY+PrMfbRHefLp7wdEjYpyZ9l4azbGHhw69KN014jRvkSD41y/daRvJmclVO/slUiSTohbOFvDUOny0BkwRtmX31mhLIGo7Knu1uon1HlE7eXa9vV9sdsv4KTcEgWCOC0LGqe9ik6bKTNnm9U+0ug/qRsZLrKic6QtROsn5ZJgixdB8aZFxeP1xU0AYqqtWUlzuRRt2WDrTFswJYgYD0FOfNkTzuUIfMy4=
    EXAMPLE_USER: AgB0bVz8EUB26GDCI2z22MpR4G6alGZza8CLKk7MxTQCraRMfj56Dm3YQAHko7ZNx73n6IkRSaujJXES9hiyeMcEhKbof1kMp3+hFwtghPnWgpbUbiatXY5wk/cAUAAsyyNQ7JARHvCriHTJqy7UdORRJU1RUwAqS9TPs78L4Aok8zThB/Aph45qbxT+y1gZ2WGjyq0oicXLVuFAOkls8lWmmacD3hgGt0HaZ1Zx6CPi1yeUyI/NZckZWYb5j1fbuD40HxhK7XSZjXHsqVmili40rj4iiEiESuRMAAU8kKxGULCpiasXbLjodvrhngmZR9wwa0NPEjWugeL7nxXdpTMm6JosD0R+hPsyrYkHG7vl+azize8jKKpiqCMwV6L9k+1t82NMOOx64UNcWnMhcyYA0uIBZYvvcSL1vuMCUBeERcw3Kuze9Vas320JdFEdQucw1jukW/4cR96ZnA6HKZVxVzXlHmE0YoRslUBLBGZ2Vk9tccvmm6PATLPcIwIthRmAwvmcErN/2N2oys8Gh4hZ7McVT4FQtDpSkrasgoHlAjMZrxhCdPU4xyYd674MD8JfKI+xQk4fjvXOXKAHJOzH+ETsh0N6PxkOtBuVz37EYLesYAp9puGX+JINfkjxO2Gf8JEK7L+ixqOqUEKYdDn4lv0rORpQUuqO3prTz5QY0hKBDQED85F3/dC/9BRc8X+P540=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: hello-world
      namespace: default

