apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hello-world
  namespace: default
spec:
  encryptedData:
    EXAMPLE_PASSWORD: AgBesarLy+mz6FznE1vgsmkydxjwh0pYg6fqR+XEYkl9sNJjfWwvOOKfEUnUSs9zvc7wNKjNhMeaioM/ghecMY0vM8L5/yRbA1qUcS0mtWX991PxhnWcweu+yiyL/724/UeKpkGb42oxt310xqvP4P7HnE9wH36y8hb43YpflvzQgI5xxOxq9SXbg4+8NDVlXgmGP+0EkZphOFPT1yT8jbNm2kw9O48AYAG6MngweQ62u+q4abGJxh5RJiDCaQ6J9VqORKIY92TuuMfx9sWTSyEMT4fGSEoCexqaaXkjgqcPqDE9NN4X/1Ubu6Ch+Z9ncjK4pOCtNz72hqOrDyNzscrTIAEKos1c2ynXbGzNkX6gVpAE8T4f7Klu+oG+HynXmP4oQtMQeXQsB/PnJA02h8DTkXSp5iPKOMJwy1LH8fP+myx17XvR2BDJ24jKrRIXZyrfubVQ+APluVx9ik0zLRG4fzrSKEwAjNxkhF/zK7pohg5tJtExzikg7jw33cM7HwiG6a6bEoiUiRn5ZGfpY485Kvzs0r50UvqtaKEQUHB2n0McQXYWu9tQ/qmwZPG0r35uoSwGJ1E1HbJS7BDyx04U9abBNej7v2+fgntrGZkWUDLoTGFCSFTmh5KPNbdunbnY6fZwJ8kEHfvBASwVZwCr21ZuCrjA4w5CiUVMuILXj2AK0rg4fY7wKzmc/NP+v4r/c38=
    EXAMPLE_USER: AgC5UpzNUaZZh/XHO78uw914derjWlVTJsONGHcKtWCaNAbNbJFegcl7TYv0XRItecGaCEoNA14pY9X9HOE6c3kJOREssZXrw7LBfGlL7L0qT+aEs5CONib7kcewRpX7vCsMyARyNjVtkVtE84521hg+xq34WcpsQshOFmD4Lww0Lb+7vQgjnEuDsvyBHwY3TXR0qq+78m/RmyUIHSF7f7rkDv5aC3r/oOJteU9XpSFmbooKS1s5WZ7UfiZOGBcLIoRt2KrIS1gEc5iyZkgT6FeuzdutQkpYAz2VKlcnhAF16T2wcTrFQTGZG2KXyKFVrxjpWhVjVACRag7KZtZt1bUQlJ9j2+dCas6kcsCfZObUEwGfvi1fLvwxvwrLHGqlIAFbYiKgYy5FKL9eeLLTb39VtEdnfNd9wWgL/WNXGo8nJNyhdxhzaH5oykF/Lv2bO7KA3oI6tMarJRRjmmUrF0envPk6YRkpR2ycO6J7PvSPLPzd9b0a6QFSP1k4BXqh6ermoTFALEEq+Tr3SBpoLrGG34+A0BevmaiVkjlZoeo6ssXPa6XKhuk2kaaLgaR/Eknt8UA7aJWH2R0sBJcaz6lF5QzcjwNmt30m3W22iexfq6BtPL/u01Ki00kcXdwhDfHv/C8oC018dYhR+nRtOuPMmCDQiitd/oE04VRF9z55JSWkRL3F6aQf/JPFXr4EVi1RmVM=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: hello-world
      namespace: default

