apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hello-world
  namespace: default
spec:
  encryptedData:
    EXAMPLE_PASSWORD: AgC/INziLkNtVSBSOotQDKqdOd/pDVw0pagKVF1rj2qX7a9bYex6a50wYEXe90lwmrAYuhql9U85H5PqutVjauk/Rr5IcATBIv8/AtuCUiQ6V069gys0cryAXP8tfH+cH/st2lwXMbf3hcMwGVJIuhfYfvBw2v/+VbunWlj/to0rxQxJcHyTDPC8ZuGemTi3g/beQaWM/UAn7VgKs3ANh4ZM3iM/kRQYk+wWyk7JuvGzn6OQmdCryg9w51c1tkSL4WFUuap4bGIIg8bhgEOSu1qFKsp85PULCrJ0VFDTLhAGk5Zrmd2SPMf/sbrkPQyaS34KAqI7Pm5Izu7tZDDRM1EhkS1eksQ/kU1hL4p/jBSVxe31lwbiOS5VTiFR244dnaz76rEBNbfft7e/3FLf24ep1E6DeHzJKVV3/gkMBsE2DxCBh1t/6lqmT5mviMP1goM1fdc/IzpW+nIDGrE2VrRF0KdYVT7UKq9gZFdDzU/MEsndZWTaq0/dtyH7LY0NysXcUtHw010ym97wJTjzX7VT/9Vg5VFZw5P8ZxamVLkXi0Xgp3GWlbjJWsket/hXKPtt4hxYGfwW2tpDG1oHANnhqr0aB45Mx96muNjOyZisF/5M+wlzAGfDrzYgboWul0R3CpvoUDsa3EkLk7b2QhW+OnGtZxb78TO9vrP2VGFpmie0acoHG43XrT93gXaRqA/Nw7o=
    EXAMPLE_USER: AgCf3oJ237ZiwTA1yu5X8m9OIztp+F40aaxDLiw+ZwFDqY4NjfwSkh3hZxYagxIXeNRRqYJD1zjGRDYbiBfbb0ClRz5ODv6I7MXvtiFnNZ99eGTIrxwYFTHU1VC+igCV6Ytv7UPSEU8wIhVr82CQG2he7/FzWR8dRIobMrfsivHB1kJ+puASYiH79pJQnpsKpZuLLGJBcyJseQujb8W7OlvDKryfwCuxqbNB27zjUljeCNdyMgep2EM6Gj05CckbhBq43EXOuQ8JLlKGnA8lLWaKTPENXYVEoly1et2ChW1mboA05enxyuGzIkMfYeYnP9cm84SljoOTA6QYBqnPBlUVxcGFJv/BkNxiL8u41/Jq6YXryvT+CLR6eDj2RCBIidyGpcEIwq6+yMFq5wlF+k/yRKkra/UrGCfhyazHQt+qrNfqIP6u8oVyPSw1b1sZMyBlx/KkNzA7uhYiR2gXuA38OKYDnYXFmptIJZUVwHZbtoSZUvsbpBSChxl7CrJZAkdlSNY1IO5HjJ2RuKz+BY0vW7tJrF/ytpGPu41NnAwCVOryyb5U3tVppvaHPIl2clrTnGuEB3VrxCSXboAKAty/MwJjhzYHjU5P8rSam7hNbSiGtSXf6fbkE/PgVJKu7ZbYtnmbVEy9kVfAp6wSXn/rPN5QHhzkrxDGAs49eP4NgCjhuRArB/S5J9sp+t29ghiFC7g=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: hello-world
      namespace: default

