apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hello-world
  namespace: default
spec:
  encryptedData:
    EXAMPLE_PASSWORD: AgAIqSnxHBin+ORuxn0PW8ORD3VdieP4LwjLWxagdxhT42hI7rPR3Pm/8B8I24pIjfJAd2zrm17+Pl7t3iD1WKY00VjFnorXmSNG93OFEPN9BiMgnF5W+jhOf5Yl7BoT7uFKZCpSdVy2IqlVnEcJA32eMjSHqrjxU1YUhdaVDkUQgdFKQUlpb5KukpLU2zIN4pMZS8iPklPYA/uWVeD0gynbFxoUJPrZuyGSVEiFJCWyz0ktrvdQoHhv3jyYXiavEAtFA+OA6TVl+7t4VgqZL8rMlYuYRJmjUqTC7M5/ZKoD+ftcGOocrEsXpADYuTYXN4qLpw89kVloyn0gq9wRVhmbcRBohzjbcVYUm5KO/Re2Wl9I7Q+6H79pwov0mm0cNLPUlNWxUaoqo4QQHHzEVyzuQXJHvEGnlpAO0xsqSxYAEQ7hYXusD88LsOJkxXV5Dp28hCKj8ljwFGTlIWYXFihGxi8FrP1Djyzd1on+oWJUWh5j2mICYdXX+kM+UtJSo8YpOvWzR6yAxj+dRUyghWsvi8klHMJG5liGAJI3/2/TISfhjF0zCMVgDeB3KHODB7MtZJJTdNIcyKO42HOtlQT2tHdrMVJtAWNcYBgOvB1SR4nC4QG5oMrUiCkRf8osmz/zUZMAYQjrSWLP1JgSuwFa8552R/CVk2/OUh5MOWuyNXbjTkqnDvh2vupzRL7WaXdQUdQ=
    EXAMPLE_USER: AgCYIIpsJvDoAJ2mF4GbKhnghyoCZV7T7PujBdBzH210ydukLhLjNX11CPDVBltH0LwyixKWvoxsciRauHxx20Wq+GQodLPB74jBijLrcHojWj35EZSe1Qdc/VDffMtpwO6J8wERLDTn8Z3o/9WEvQh3WEZG0y8FyeqHyT1oNGPpnG6F3CG4lgd9Eh1Jw5zh0SyumVrGr6NB3c4vYtfrfF4WEz0DWCTdSofj8CVxl6oB47dqDsrMV5IrstsmOxlBwxOL4Ifr2+F02fzerx/QXUqBX5of/dR6oZ2NRCQebbEfzfsMoaBddJOSSpIveZjYgPtyJwmOa5z2ACReKb6RzOdwhGgvgq74Vy5Vt7l/rVHJCopHtYQBoUUQLHxpAAoI6zF4+7aO1JeQTkYCArOA98fPQWqRZjZhBU0S7ETNYkrwWdlFgD39nnIA4+Dcsh64YYZxbgBe3O6rTmKRncFJD1SgfEWvCD+NtyszxMHbzOtr4bTwvN+T2gKdMgT1Im9hZpy1bIyNeKqpwqEQCxXB+WmYk9dix3NEhbvjOYNxm8T2C6YXyqZ7v0GwMrXObvkM2tvxqMEovecNOUMPRwIW2Aif4J7KRHRBUSB2VbNxmrQarTTZl/BIqv50M1c+Sw/Hae2hNnvdiddcLTvZskRGBeJwsyZxM3FIN3gO2iTlZq0T1nH8S5Rbg2nd6JE7sYh71QtHVNU=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: hello-world
      namespace: default

