---

ansible_user: root # TODO: use unprivileged user
ansible_python_interpreter: /usr/bin/python3

k3s_version: v1.24.3+k3s1
k3s_become: true

extra_server_args: ""
extra_agent_args: ""
k3s_etcd_datastore: true
k3s_server_manifests_templates:
  - "manifests/calico/tigera-operator.yml"
  - "manifests/calico/calico-custom-resources.yml"

k3s_server:
  cluster-cidr: 10.42.0.0/16
  flannel-backend: "none"
k3s_agent:
