#!/bin/bash

curl -fsS -m 10 --retry 5 -o /dev/null $PING_URL/start

output=$(btrfs balance start -musage=50 -dusage=50 /var/anubis)

curl -fsS -m 10 --retry 5 --data-raw "$output" -o /dev/null $PING_URL/$?
