apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik
spec:
  chart: traefik
  repo: https://helm.traefik.io/traefik
  targetNamespace: traefik
  valuesContent: |-
    deployment:
      replicas: 2
    ports:
      web:
        redirectTo: websecure
    additionalArguments:
      - "--log.level=DEBUG"
      - "--accesslog=true"
      - "--accesslog.format=json"
      # - "--certificatesresolvers.le.acme.email=garrit@slashdev.space"
      # - "--certificatesresolvers.le.acme.storage=/data/acme.json"
      # - "--certificatesresolvers.le.acme.tlschallenge=true"
      # - "--certificatesresolvers.le.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory"
    metrics:
      prometheus:
        addRoutersLabels: true
