apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik
spec:
  chart: traefik
  repo: https://helm.traefik.io/traefik
  targetNamespace: traefik
  valuesContent: |-
    deployment:
      replicas: 2
    additionalArguments:
      - "--log.level=DEBUG"
      - "--accesslog=true"
      - "--accesslog.format=json"
    metrics:
      prometheus:
        addRoutersLabels: true
