apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra
  namespace: infra-base
spec:
  path: ./k8s/clusters/INVALID
  interval: 60m0s
  timeout: 10m0s
  retryInterval: 5m0s
  prune: true
  force: true
  sourceRef:
    kind: GitRepository
    namespace: flux-system
    name: flux-system
  decryption:
   provider: sops
   secretRef:
     name: infra-sops-age-key
