apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ingress-nginx
spec:
  interval: 1m
  url: https://kubernetes.github.io

---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ingress-nginx
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: v4.10.0
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
      interval: 1m
  values:
    controller:
      replicaCount: 1
      metrics:
        enabled: true
        service:
          annotations:
            prometheus.io/port: "9100"
            prometheus.io/scrape: "true"
