apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: node-exporter
  name: node-exporter
  namespace: monitoring
spec:
  ports:
  - name: metrics
    port: 9100
    targetPort: metrics
  selector:
    app.kubernetes.io/name: node-exporter