apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  interval: 5m
  chart:
    spec:
      chart: cert-manager
      version: v1.9.1
      sourceRef:
        kind: HelmRepository
        name: cert-manager
      interval: 1m
  values:
    installCRDs: true